easy_admin:
    entities:
        - App\Entity\Personnages
        - App\Entity\Royaumes
        - App\Entity\Saison
        - App\Entity\Musique
        - App\Entity\Produit
        - App\Entity\Evenements
        - App\Entity\Spinoff
